#!/bin/bash
argnum=1
if [ $# != $argnum ];then
	echo "Usage: `basename $0` [filename] [receiver_email]"
	exit 1
fi

filename=$1
[ ! -e $filename ] && {
    echo "$filename不存在"
    exit 1
}

#压缩
if [ -d $filename ];then
    abs_dir=`readlink -f $filename`
    filename="`basename $abs_dir`.tar.gz"
    cd `dirname $abs_dir`
    tar -zcvf  $filename  "`basename $abs_dir`"  &> /dev/null 
fi

#依赖sendEmail，需安装sendEmail
sendEmail=`which sendEmail`

#发送邮件的邮箱
fromEmailAddress="黄骏丰<13640203159@163.com>"
toEmailAddress="863472527@qq.com"
smtpServer="smtp.163.com"
#发送邮件的邮箱
emailUser="13640203159@163.com"
#邮箱许可码
emailPass="1234567890abcde"
emailTitle="a email from `uname -rn`"
emailInfo="`date +%F" "%T`"

$sendEmail -f $fromEmailAddress \
-t $toEmailAddress \
-s $smtpServer \
-xu $emailUser \
-xp $emailPass \
-u $emailTitle \
-m $emailInfo \
-o tls=no \
-o message-charset=gbk \
-a $filename

ret=$?

exit $ret
